version: "3"

services:
  # =====================================
  # applications section
  # =====================================
  keycloak_app:
    image: quay.io/keycloak/keycloak:22.0
    platform: linux/amd64
    command: start-dev
    container_name: keycloak_app
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak_db:3306/keycloak_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    networks:
      - routines-app-net

  # =====================================
  # databases section
  # =====================================
  routines_db:
    platform: linux/x86_64
    image: mysql:8.2.0
    container_name: routines_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routines_db
      MYSQL_PASSWORD: root
    ports:
      - 33009:3306
    volumes:
      - .docker/dbdata/routines:/var/lib/mysql
    networks:
      - routines-app-net

  keycloak_db:
    image: mysql:8.2.0
    platform: linux/amd64
    container_name: keycloak_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_PASSWORD: root
    ports:
      - 33066:3306
    volumes:
      - ./.docker/dbdata/keycloak:/var/lib/mysql
    networks:
      - routines-app-net

# =====================================
# network section
# =====================================
networks:
  routines-app-net:
    driver: bridge
